galaxy_info:
  role_name: nginx_docker
  namespace: bushetaa
  author: Bushetaa
  description: A role to install and run NGINX in Docker
  company: your_company_name
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8

dependencies: []
